# Setup
name: ElixirSchool
url: https://elixirschool.com
permalink: /blog/:title/
default_lang: en
exclude_from_localization: []

# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

plugins:
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-sitemap
  - kramdown
  - uglifier
  - jekyll-archives

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'CONTRIBUTING.md', 'Gemfile', 'Gemfile.lock', 'GLOSSARY', 'Procfile', 'Rakefile', 'README.md', 'vendor', 'LICENSE']
assets:
  compress:
    css: sass
    js:  uglifier
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

sitemap:
  file: '/sitemap.xml'
  include_posts:
    - '/index.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'

elixir:
  version: 1.10.1

erlang:
  OTP: 22.0
  erts: 10.5.3

jekyll-archives:
  enabled: ['categories', 'tags', 'year']
  layout: archive
  permalinks:
    year: '/blog/years/:year/'
    category: '/blog/categories/:name/'
    tag: '/blog/tags/:name/'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Helpers
empty_array: []
